Update minimum Go version to 1.12
At least with the golang Docker image 1.11.4 we were having linker issues (libobjectbox.so: undefined reference to `logf@GLIBC_2.27'), so it seems reasonable to require at least 1.12, which is ancient already.